spring.application.name=fsweb-s17d1
server.port=8585

spring.devtools.restart.quite-period=1000
spring.devtools.restart.pool-interval=2000

project.developer.fullname=SpringBoot-Proje1
course.name=BackendJava